### ISSUE TITLE
So how do you run this thing?

### ISSUE THREAD

**Issue by dbackeus** [zhongqf/meteor-vue-redux-example#1]
Was curious to try this out but couldn't get it running.

First tried running `meteor` which seemed the most obvious thing to do with a meteor app which gave me a blank screen.

Then noticed that you got that `.client` directory so tried running `npm run dev` and `npm start` etc from there but that didn't pan out either...

**Comment by zhongqf** [comment]
Run `npm run dev` in `.client`, then run `meteor` in another console terminal.
