### ISSUE TITLE
This is more of a question than an issue - Multiple collections

### ISSUE THREAD

**Issue by genyded** [zhongqf/meteor-vue-redux-example#2]
This is really a question, but not sure where else to ask it... If you have multiple collections, should you subscribe to them all in the single index.js file? Also when connecting the store to Meteor you mention Do not connect to Meteor twice, what do you mean by that?

Thanks!

**Comment by zhongqf** [comment]
```
If you have multiple collections, should you subscribe to them all in the single index.js file? 
```

As my know, it is a good practice. (maybe not in index.js. For example, manage all you subscription in a single subscriptins.js is better). Subscribing is completely Meteor's behavior, have nothing to do with meteoredux library or this example. You do not get data to be updated if you having not subscribed to a collection.

```
Also when connecting the store to Meteor you mention Do not connect to Meteor twice, what do you mean by that?
```

connectToMeteor will product a global instance internally, so second time you connect to meteor, you will get an error.
